const DB=window.__STAGE_DATA__;

 const XAX=[["A", 0.0], ["B", 2984.661849899101], ["C", 4900.1618498992175], ["D", 5485.969142347458], ["E", 8749.20077013271], ["F", 9724.014933659579], ["G", 14689.023254005122], ["H", 19500.161849899217], ["I", 21000.161849899217]]; const YAX=[["1", 0.0], ["2", 3600.0], ["3", 6425.0], ["4", 7079.999999795007], ["5", 10044.595998688994], ["6", 10700.0], ["7", 12550.040094760494]]; const rows=DB.rows; const byGrid=Object.fromEntries(rows.map(r=>[r.grid_ref,r]));
let selected=new Set(); let focus='A1';
const colors={C1:'#2563eb',C2:'#16a34a',C3:'#d97706',C4:'#be185d'};
function esc(s){return String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));}
function setPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.p===id));renderAll();}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setPage(b.dataset.p));
function toggle(g){focus=g;if(selected.has(g))selected.delete(g);else selected.add(g);renderAll();}
function selectAll(){selected=new Set(rows.map(r=>r.grid_ref));renderAll();} function clearSel(){selected.clear();renderAll();}
function selectSameType(){const f=byGrid[focus]; if(!f)return; selected=new Set(rows.filter(r=>r.column_type===f.column_type).map(r=>r.grid_ref));renderAll();}
function selRows(){return rows.filter(r=>selected.has(r.grid_ref));}
function sums(){const rr=selRows();return {count:rr.length,rcc:rr.reduce((a,r)=>a+r.rcc_m3,0),cement:rr.reduce((a,r)=>a+r.cement_bags,0),sand:rr.reduce((a,r)=>a+r.sand_m3,0),agg:rr.reduce((a,r)=>a+r.aggregate_m3,0)};}
function selectorHTML(){return rows.map(r=>`<label class="selrow"><input type="checkbox" ${selected.has(r.grid_ref)?'checked':''} onchange="toggle('${r.grid_ref}')"><b>${r.grid_ref}</b><span>${r.column_type}</span><span class="muted">${r.section} · ${r.support_class}</span></label>`).join('');}
function planSVG(){const W=1100,H=720,mx=80,my=55;const xmin=XAX[0][1],xmax=XAX[XAX.length-1][1],ymin=YAX[0][1],ymax=YAX[YAX.length-1][1];const sx=x=>mx+(x-xmin)/(xmax-xmin)*(W-2*mx);const sy=y=>H-my-(y-ymin)/(ymax-ymin)*(H-2*my);let s=`<svg viewBox="0 0 ${W} ${H}" aria-label="Narayani column spatial plan">`;
for(const [l,x] of XAX)s+=`<line class="axis" x1="${sx(x)}" y1="${my}" x2="${sx(x)}" y2="${H-my}"/><text class="axislabel" x="${sx(x)}" y="${my-15}" text-anchor="middle">${l}</text>`;
for(const [l,y] of YAX)s+=`<line class="axis" x1="${mx}" y1="${sy(y)}" x2="${W-mx}" y2="${sy(y)}"/><text class="axislabel" x="${mx-18}" y="${sy(y)+4}" text-anchor="end">${l}</text>`;
s+=`<text x="${W-90}" y="35" font-size="15" font-weight="700">N ↑</text>`;
for(const r of rows){const x=sx(r.x_mm),y=sy(r.y_mm),is=selected.has(r.grid_ref),dim=selected.size&&!is?' unselected':'';const cls=`node ${r.column_type.toLowerCase()}${is?' sel':''}${dim}`;if(r.column_type==='C4')s+=`<g class="${cls}" onclick="toggle('${r.grid_ref}')"><circle class="shape" cx="${x}" cy="${y}" r="11"/><text class="nlabel" x="${x+14}" y="${y-8}">${r.grid_ref}/${r.column_type}</text></g>`;else s+=`<g class="${cls}" onclick="toggle('${r.grid_ref}')"><rect class="shape" x="${x-10}" y="${y-10}" width="20" height="20" rx="2"/><text class="nlabel" x="${x+14}" y="${y-8}">${r.grid_ref}/${r.column_type}</text></g>`;}
return s+'</svg>';}
function metricsHTML(){const m=sums();return `<div class="metric"><span class="muted">Supports</span><b>${m.count}</b></div><div class="metric"><span class="muted">M20 RCC</span><b>${m.rcc.toFixed(4)} m³</b></div><div class="metric"><span class="muted">Cement</span><b>${m.cement.toFixed(2)} bags</b></div><div class="metric"><span class="muted">Sand</span><b>${m.sand.toFixed(3)} m³</b></div><div class="metric"><span class="muted">Aggregate</span><b>${m.agg.toFixed(3)} m³</b></div>`;}
function focusedText(){const r=byGrid[focus];return r?`Focused: <b>${r.grid_ref}</b> · ${r.column_type} · ${r.section} · ${r.support_class} · stem ${r.stem_height_footing_top_to_plinth_m.toFixed(3)} m · RCC ${r.rcc_m3.toFixed(4)} m³`:'';}
function crossSVG(r){let s='<svg viewBox="0 0 320 260">';s+=`<text x="12" y="22" font-size="14" font-weight="700">Cross-section ${r.column_type} — ${r.section}</text>`;if(r.column_type==='C4'){const cx=160,cy=135,R=85,tR=62,bR=52;s+=`<circle cx="${cx}" cy="${cy}" r="${R}" fill="#f1f5f9" stroke="#334155" stroke-width="3"/><circle cx="${cx}" cy="${cy}" r="${tR}" fill="none" stroke="#7c3aed" stroke-width="3"/>`;for(let i=0;i<8;i++){let a=2*Math.PI*i/8-Math.PI/2,x=cx+bR*Math.cos(a),y=cy+bR*Math.sin(a);s+=`<circle cx="${x}" cy="${y}" r="5" fill="#be185d"/>`;}s+=`<text x="12" y="244" font-size="11">8T12 · circular T8 tie · cover 40 mm</text>`;}else{const x=65,y=50,w=190,h=190,inset=30; s+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="#f1f5f9" stroke="#334155" stroke-width="3"/><rect x="${x+inset}" y="${y+inset}" width="${w-2*inset}" height="${h-2*inset}" fill="none" stroke="#7c3aed" stroke-width="3"/><line x1="${160}" y1="${y+inset}" x2="${160}" y2="${y+h-inset}" stroke="#7c3aed" stroke-width="2"/>`;let pts=[[x+inset+10,y+inset+10],[160,y+inset+10],[x+w-inset-10,y+inset+10],[x+w-inset-10,145],[x+w-inset-10,y+h-inset-10],[160,y+h-inset-10],[x+inset+10,y+h-inset-10],[x+inset+10,145]];pts.forEach((p,i)=>{let fill='#2563eb';if(r.column_type==='C3')fill='#d97706';if(r.column_type==='C2')fill=(i%2===0?'#166534':'#16a34a');s+=`<circle cx="${p[0]}" cy="${p[1]}" r="6" fill="${fill}"/>`;});s+=`<text x="12" y="22" font-size="14" font-weight="700">Cross-section ${r.column_type} — 400×400</text>`;s+=`<text x="12" y="255" font-size="11">${r.longitudinal_reinforcement} · outer T8 hoop + crosstie · cover 40 mm</text>`;if(r.column_type==='C2')s+=`<text x="12" y="240" font-size="11">T20 corners · T16 mid-faces (code-backed placement provenance)</text>`;}return s+'</svg>';}
function longSVG(r){const h=r.stem_height_footing_top_to_plinth_m;let s='<svg viewBox="0 0 420 330">';s+=`<text x="12" y="22" font-size="14" font-weight="700">Footing-top → plinth column lift</text><line x1="35" y1="90" x2="390" y2="90" stroke="#0f172a" stroke-width="2"/><text x="38" y="80" font-size="11">PLINTH 0.000</text><line x1="35" y1="270" x2="390" y2="270" stroke="#64748b" stroke-width="2"/><text x="38" y="292" font-size="11">FOOTING TOP −${h.toFixed(3)} m</text><rect x="145" y="90" width="130" height="180" fill="#bfdbfe" fill-opacity=".65" stroke="#2563eb" stroke-width="3"/>`;
for(let y=102;y<267;y+=15)s+=`<line x1="150" y1="${y}" x2="270" y2="${y}" stroke="#7c3aed" stroke-width="1.5"/>`;
for(const x of [164,190,230,256])s+=`<line x1="${x}" y1="50" x2="${x}" y2="284" stroke="#dc2626" stroke-width="3"/><line x1="${x}" y1="50" x2="${x}" y2="35" stroke="#dc2626" stroke-width="2" stroke-dasharray="5 4"/>`;
s+=`<text x="285" y="130" font-size="11">M20 RCC stage</text><text x="285" y="148" font-size="11">T8 @125 c/c to plinth</text><text x="285" y="166" font-size="11">${esc(r.longitudinal_reinforcement)} continuity bars</text><text x="285" y="184" font-size="11">M50 first-lift BBS = bar authority</text><text x="285" y="202" font-size="11">RCC ${r.rcc_m3.toFixed(4)} m³</text>`;return s+'</svg>';}
function detailCard(r){return `<div class="detailCard"><b>${r.grid_ref} · ${r.column_type}</b> <span class="muted">${r.section} · ${r.support_class}</span><div class="detailViews">${longSVG(r)}${crossSVG(r)}</div><table class="tbl"><tr><th>Field</th><th>Value</th></tr><tr><td>Stem height</td><td>${r.stem_height_footing_top_to_plinth_m.toFixed(3)} m</td></tr><tr><td>M20 RCC</td><td>${r.rcc_m3.toFixed(6)} m³</td></tr><tr><td>Cement</td><td>${r.cement_bags.toFixed(3)} bags</td></tr><tr><td>Sand</td><td>${r.sand_m3.toFixed(4)} m³</td></tr><tr><td>Aggregate</td><td>${r.aggregate_m3.toFixed(4)} m³</td></tr><tr><td>Longitudinal</td><td>${r.longitudinal_reinforcement}</td></tr><tr><td>Ties</td><td>${r.subplinth_ties}</td></tr></table></div>`;}
function elevSVG(mode){const r=byGrid[focus];const axes=mode==='X'?XAX:YAX;const selLabel=mode==='X'?focus.replace(/\d+/,''):focus.replace(/\D+/g,'');const W=780,H=520,l=70,rr=25,t=35,b=55;const min=axes[0][1],max=axes[axes.length-1][1];const sx=v=>l+(v-min)/(max-min)*(W-l-rr);const zmin=-1700,zmax=9300;const sy=z=>H-b-(z-zmin)/(zmax-zmin)*(H-t-b);let s=`<svg viewBox="0 0 ${W} ${H}">`;for(const [lab,pos] of axes){let x=sx(pos);s+=`<line x1="${x}" y1="${t}" x2="${x}" y2="${H-b}" stroke="#cbd5e1" stroke-dasharray="5 5"/><text x="${x}" y="${H-28}" text-anchor="middle" font-size="11">${lab}</text>`;}for(const [z,label] of [[0,'Plinth'],[3048,'+3048'],[6096,'+6096'],[9144,'+9144']]){let y=sy(z);s+=`<line x1="${l}" y1="${y}" x2="${W-rr}" y2="${y}" stroke="#94a3b8"/><text x="${l-8}" y="${y+4}" text-anchor="end" font-size="10">${label}</text>`;}let pair=axes.find(a=>a[0]===selLabel);if(pair){let x=sx(pair[1]);let bottom=sy(-r.stem_height_footing_top_to_plinth_m*1000),pl=sy(0);s+=`<rect x="${x-9}" y="${pl}" width="18" height="${bottom-pl}" fill="#2563eb" opacity=".8"/><line x1="${x}" y1="${sy(9144)}" x2="${x}" y2="${pl}" stroke="#2563eb" stroke-width="3" stroke-dasharray="8 5"/><circle cx="${x}" cy="${pl}" r="5" fill="#dc2626"/><text x="${x+12}" y="${pl+18}" font-size="11" font-weight="700">${focus} M60 lift</text>`;}s+=`<text x="${l}" y="18" font-size="12" font-weight="700">${mode==='X'?'A–I':'1–7'} grid-linked elevation · focus ${focus}</text></svg>`;return s;}
function renderAll(){['plan1','plan2','plan3','plan4','plan5'].forEach(id=>{let e=document.getElementById(id);if(e)e.innerHTML=planSVG();});['sel2','sel3','sel4'].forEach(id=>{let e=document.getElementById(id);if(e)e.innerHTML=selectorHTML();});['metrics2','metrics3','metrics4'].forEach(id=>{let e=document.getElementById(id);if(e)e.innerHTML=metricsHTML();});let f=focusedText();['p1focus','focus4','focus5'].forEach(id=>{let e=document.getElementById(id);if(e)e.innerHTML=f;});let b=document.getElementById('break2');if(b){const rr=selRows();const c={};rr.forEach(r=>c[r.column_type]=(c[r.column_type]||0)+1);b.innerHTML='<h4>Type breakdown</h4>'+Object.entries(c).map(([k,v])=>`<div>${k}: ${v}</div>`).join('');}let o=document.getElementById('order3');if(o){const m=sums();o.innerHTML=`<table class="tbl"><tr><th>Material</th><th>Selected demand</th></tr><tr><td>M20 RCC</td><td>${m.rcc.toFixed(4)} m³</td></tr><tr><td>Cement</td><td>${m.cement.toFixed(2)} bags</td></tr><tr><td>Sand</td><td>${m.sand.toFixed(3)} m³</td></tr><tr><td>Aggregate</td><td>${m.agg.toFixed(3)} m³</td></tr></table>`;}let d=document.getElementById('details4');if(d){const rr=selRows();d.innerHTML=rr.length?rr.map(detailCard).join(''):`<div class="muted" style="padding:12px">Select one or more supports from the list or full map to generate local column-lift details.</div>`;}let ex=document.getElementById('elevX');if(ex)ex.innerHTML=elevSVG('X');let ey=document.getElementById('elevY');if(ey)ey.innerHTML=elevSVG('Y');}
renderAll();

