

const SNAPSHOT=JSON.parse(document.getElementById('m70-json-snapshot').textContent);
const DB=SNAPSHOT.spatial_db;
const FAB=SNAPSHOT.fabrication;
const rows=DB.rows, byId=Object.fromEntries(rows.map(r=>[r.run_id,r]));let selected=new Set(),focus=rows[0].run_id;
const X=DB.grid.x_mm,Y=DB.grid.y_mm;const xmin=Math.min(...Object.values(X)),xmax=Math.max(...Object.values(X)),ymin=Math.min(...Object.values(Y)),ymax=Math.max(...Object.values(Y));
function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function xy(x,y){return [70+(x-xmin)/(xmax-xmin)*820,680-(y-ymin)/(ymax-ymin)*560]}
function toggle(id){selected.has(id)?selected.delete(id):selected.add(id);focus=id;renderAll()}
function clearSel(){selected.clear();renderAll()} function selectAll(){rows.forEach(r=>selected.add(r.run_id));renderAll()}
function selRows(){return rows.filter(r=>selected.has(r.run_id))}
function focusFab(id){focus=id;renderAll()}
function planSVG(mode='multi'){let s='<svg viewBox="0 0 960 760">';for(const [lab,p] of Object.entries(X)){const [px]=xy(p,ymin);s+=`<line class="axis" x1="${px}" y1="70" x2="${px}" y2="700"/><text class="axislabel" x="${px}" y="52" text-anchor="middle">${lab}</text>`}for(const [lab,p] of Object.entries(Y)){const [,py]=xy(xmin,p);s+=`<line class="axis" x1="50" y1="${py}" x2="920" y2="${py}"/><text class="axislabel" x="35" y="${py+4}" text-anchor="end">${lab}</text>`}for(const r of rows){let [x1,y1]=xy(r.x1_mm,r.y1_mm),[x2,y2]=xy(r.x2_mm,r.y2_mm);let cls,click;if(mode==='focus'){cls='beam '+(focus===r.run_id?'sel':'unselected');click=`focusFab('${r.run_id}')`}else{cls='beam '+(selected.has(r.run_id)?'sel':(selected.size?'unselected':''));click=`toggle('${r.run_id}')`}s+=`<line class="${cls}" data-id="${r.run_id}" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" onclick="${click}"/>`;let mx=(x1+x2)/2,my=(y1+y2)/2;s+=`<text class="runlabel" x="${mx+5}" y="${my-7}">${r.run_key}</text>`}s+='<text x="865" y="34" font-size="14" font-weight="700">N ↑</text></svg>';return s}
function selectorHTML(){return rows.map(r=>`<label class="selrow ${focus===r.run_id?'focus':''}"><input type="checkbox" ${selected.has(r.run_id)?'checked':''} onchange="toggle('${r.run_id}')"><b>${r.run_key}</b><span class="muted">${r.from_grid}→${r.to_grid} · ${r.centerline_length_m.toFixed(3)} m</span></label>`).join('')}
function sums(){const rr=selRows();return {n:rr.length,L:rr.reduce((a,r)=>a+r.centerline_length_m,0),rcc:rr.reduce((a,r)=>a+r.rcc_m3,0),cem:rr.reduce((a,r)=>a+r.cement_bags,0),sand:rr.reduce((a,r)=>a+r.sand_m3,0),agg:rr.reduce((a,r)=>a+r.aggregate_m3,0),links:rr.reduce((a,r)=>a+r.t8_link_count,0),t8kg:rr.reduce((a,r)=>a+r.t8_installed_kg,0),preT12:rr.reduce((a,r)=>a+r.mainbar_preterminal_fabrication_m,0)}}
function metricsHTML(){const m=sums();return `<div class="metric"><span class="muted">Runs</span><b>${m.n}</b></div><div class="metric"><span class="muted">Centerline</span><b>${m.L.toFixed(3)} m</b></div><div class="metric"><span class="muted">M20 RCC</span><b>${m.rcc.toFixed(4)} m³</b></div><div class="metric"><span class="muted">T8 links</span><b>${m.links}</b></div><div class="metric"><span class="muted">Cement</span><b>${m.cem.toFixed(2)} bags</b></div><div class="metric"><span class="muted">T8 installed</span><b>${m.t8kg.toFixed(2)} kg</b></div>`}
function focusText(){const r=byId[focus];return `<b>${r.run_key}</b> · ${r.from_grid}→${r.to_grid} · ${r.centerline_length_m.toFixed(3)} m · RCC ${r.rcc_m3.toFixed(4)} m³ · T8 links ${r.t8_link_count}`}
function crossSVG(r){return `<svg viewBox="0 0 330 280"><text x="12" y="22" font-size="14" font-weight="700">PB section 230×300</text><rect x="75" y="45" width="180" height="210" fill="#dbeafe" stroke="#334155" stroke-width="3"/><rect x="96" y="66" width="138" height="168" fill="none" stroke="#7c3aed" stroke-width="3"/><circle cx="112" cy="84" r="6" fill="#dc2626"/><circle cx="165" cy="84" r="6" fill="#dc2626"/><circle cx="218" cy="84" r="6" fill="#dc2626"/><circle cx="112" cy="216" r="6" fill="#dc2626"/><circle cx="165" cy="216" r="6" fill="#dc2626"/><circle cx="218" cy="216" r="6" fill="#dc2626"/><text x="12" y="272" font-size="11">3T12 top + 3T12 bottom · T8 closed link · cover 25 mm</text></svg>`}
function longSVG(r){let L=680;return `<svg viewBox="0 0 760 300"><text x="12" y="22" font-size="14" font-weight="700">Longitudinal run ${r.run_key} · ${r.from_grid}→${r.to_grid}</text><line x1="40" y1="150" x2="720" y2="150" stroke="#60a5fa" stroke-width="54"/><line x1="40" y1="120" x2="720" y2="120" stroke="#dc2626" stroke-width="3"/><line x1="40" y1="130" x2="720" y2="130" stroke="#dc2626" stroke-width="3"/><line x1="40" y1="140" x2="720" y2="140" stroke="#dc2626" stroke-width="3"/><line x1="40" y1="160" x2="720" y2="160" stroke="#dc2626" stroke-width="3"/><line x1="40" y1="170" x2="720" y2="170" stroke="#dc2626" stroke-width="3"/><line x1="40" y1="180" x2="720" y2="180" stroke="#dc2626" stroke-width="3"/>${Array.from({length:31},(_,i)=>{let x=55+i*21.5;let dense=x<160||x>600; if(!dense&&i%2)return ''; return `<line x1="${x}" y1="106" x2="${x}" y2="194" stroke="#7c3aed" stroke-width="2"/>`}).join('')}<line x1="40" y1="88" x2="40" y2="210" stroke="#0f172a" stroke-width="4"/><line x1="720" y1="88" x2="720" y2="210" stroke="#0f172a" stroke-width="4"/><text x="52" y="235" font-size="11">Dense zone: ≤100 mm c/c for 600 mm from structural joint</text><text x="265" y="255" font-size="11">Middle: ≤150 mm c/c</text><text x="520" y="235" font-size="11">Dense zone: ≤100 mm c/c</text><text x="12" y="286" font-size="11">Diagram explains zoning; exact count for this run = ${r.t8_link_count} T8 links from frozen final BBS.</text></svg>`}
function detailCard(r){return `<div class="detailCard"><b>${r.run_key}</b> <span class="muted">${r.from_grid}→${r.to_grid}</span><div class="detailViews">${longSVG(r)}${crossSVG(r)}</div><table class="tbl"><tr><th>Field</th><th>Value</th></tr><tr><td>Centerline</td><td>${r.centerline_length_m.toFixed(4)} m</td></tr><tr><td>M20 RCC</td><td>${r.rcc_m3.toFixed(5)} m³</td></tr><tr><td>Main bars</td><td>${r.main_rebar}</td></tr><tr><td>Pre-terminal T12 working fabrication</td><td>${r.mainbar_preterminal_fabrication_m.toFixed(3)} m</td></tr><tr><td>Pre-terminal splices (6 bars)</td><td>${r.splices_preterminal_for_6_bars}</td></tr><tr><td>T8 links</td><td>${r.t8_link_count} × 1000 mm</td></tr><tr><td>Link zoning</td><td>${r.link_zoning}</td></tr></table></div>`}
function elevSVG(){const r=byId[focus];const W=820,H=430,pl=300;let s=`<svg viewBox="0 0 ${W} ${H}"><text x="20" y="24" font-size="13" font-weight="700">Building elevation context · ${r.run_key}</text>`;for(const [z,l] of [[0,'PLINTH'],[3048,'+3048'],[6096,'+6096'],[9144,'+9144']]){let y=pl-z/9144*230;s+=`<line x1="65" y1="${y}" x2="790" y2="${y}" stroke="#cbd5e1"/><text x="55" y="${y+4}" text-anchor="end" font-size="10">${l}</text>`}s+=`<line x1="100" y1="${pl}" x2="750" y2="${pl}" stroke="#f59e0b" stroke-width="12"/><text x="110" y="${pl-12}" font-size="11" font-weight="700">Selected plinth-beam run is constructed at plinth level</text><line x1="170" y1="${pl}" x2="170" y2="70" stroke="#2563eb" stroke-width="3" stroke-dasharray="8 5"/><line x1="680" y1="${pl}" x2="680" y2="70" stroke="#2563eb" stroke-width="3" stroke-dasharray="8 5"/><text x="100" y="360" font-size="11">Plan remains the authority for exact horizontal endpoints (${r.from_grid}→${r.to_grid}); elevation shows its vertical stage.</text></svg>`;return s}

function fabFocusRun(){return rows.find(r=>r.run_id===focus)||rows[0]}
function fmtm(mm){return (mm/1000).toFixed(3)+' m'}
let fab6Global=false,fab7Global=false,fab8Global=false;
function toggleFab6Scope(){fab6Global=!fab6Global;renderFabPages()}
function toggleFab7Scope(){fab7Global=!fab7Global;renderFabPages()}
function toggleFab8Scope(){fab8Global=!fab8Global;renderFabPages()}
function pieceRun(id){const p=FAB.proof.fabricated_pieces.find(x=>x.piece_id===id);if(p)return p.run_id;const t=FAB.t8.links.find(x=>x.link_id===id);return t?t.run_id:''}
function selectedT12Pieces(runId){return FAB.proof.fabricated_pieces.filter(x=>x.run_id===runId).sort((a,b)=>a.face.localeCompare(b.face)||a.bar_no-b.bar_no||a.piece_no-b.piece_no)}
function selectedT12Stocks(runId){const ids=new Set(selectedT12Pieces(runId).map(x=>x.stock_rod_id));return FAB.proof.T12_stock_rods.filter(x=>ids.has(x.stock_rod_id))}
function relatedLeftovers(runId){return FAB.inventory.leftovers.filter(x=>x.origin_cut_piece_ids.some(id=>pieceRun(id)===runId))}
function barLapSVG(r){const events=FAB.proof.splice_events.filter(x=>x.run_id===r.run_id),L=r.centerline_length_m*1000,W=940,left=145,right=905,usable=right-left;let s=`<svg viewBox="0 0 ${W} 335"><text x="18" y="24" font-size="13" font-weight="700">${r.run_id} · ${r.from_grid}→${r.to_grid} · ${r.centerline_length_m.toFixed(3)} m</text><text x="18" y="42" font-size="11" fill="#64748b">Red bands = 720 mm legal lap zones. Click another beam on the plan to replace this diagram.</text>`;const lines=[['TOP',1],['TOP',2],['TOP',3],['BOTTOM',1],['BOTTOM',2],['BOTTOM',3]];lines.forEach((q,i)=>{const y=78+i*40;s+=`<text x="18" y="${y+4}" font-size="11" font-weight="700">${q[0]} B${q[1]}</text><line x1="${left}" y1="${y}" x2="${right}" y2="${y}" stroke="#334155" stroke-width="5" stroke-linecap="round"/>`;events.filter(e=>e.face===q[0]&&e.bar_no===q[1]).forEach(e=>{const x1=left+usable*e.start_mm/L,x2=left+usable*e.end_mm/L;s+=`<rect x="${x1}" y="${y-10}" width="${Math.max(3,x2-x1)}" height="20" rx="4" fill="#ef4444" opacity=".72"/><text x="${x1}" y="${y-14}" font-size="9" fill="#991b1b">${(e.start_mm/1000).toFixed(3)}m</text>`})});s+=`<text x="${left}" y="322" font-size="10">0</text><text x="${right}" y="322" text-anchor="end" font-size="10">${r.centerline_length_m.toFixed(3)} m</text></svg>`;return s}
function renderFabPages(){
 const P=FAB.proof,T=FAB.t8,I=FAB.inventory,r=fabFocusRun();
 const pieces=selectedT12Pieces(r.run_id),sp=P.splice_events.filter(x=>x.run_id===r.run_id),stocks=selectedT12Stocks(r.run_id),selCut=pieces.reduce((a,x)=>a+x.cut_length_mm,0);
 const f6=document.getElementById('fab6focus');if(f6)f6.innerHTML=`<b>Selected beam: ${r.run_id}</b> · ${r.from_grid}→${r.to_grid} · ${r.centerline_length_m.toFixed(3)} m · ${r.main_rebar}`;
 const m6=document.getElementById('fab6metrics');if(m6)m6.innerHTML=`<div class="metric"><b>${sp.length}</b><span>lap events on beam</span></div><div class="metric"><b>${pieces.length}</b><span>T12 fabricated pieces</span></div><div class="metric"><b>${(selCut/1000).toFixed(3)} m</b><span>selected piece cuts</span></div><div class="metric"><b>${new Set(pieces.map(x=>x.stock_rod_id)).size}</b><span>parent rods touched</span></div>`;
 const g6=document.getElementById('fab6globalnote');if(g6)g6.innerHTML=`<b>Whole M70 context:</b> ${P.optimization.T12_stock_rods_12m} × 12 m T12 rods · ${P.optimization.T12_fabrication_demand_m.toFixed(3)} m demand · ${P.optimization.T12_offcut_m.toFixed(3)} m leftover. These are global, not ${r.run_id}-only values.`;
 const v6=document.getElementById('fab6barviz');if(v6)v6.innerHTML=barLapSVG(r);
 const b6=document.getElementById('fab6bars');if(b6)b6.innerHTML=`<table class="tbl"><tr><th>Face / bar</th><th>Piece</th><th>Cut length</th><th>Parent 12 m rod</th><th>Lap starts</th></tr>${pieces.map(x=>`<tr><td>${x.face} B${x.bar_no}</td><td>${x.piece_id}</td><td>${x.cut_length_mm} mm</td><td>${x.stock_rod_id}</td><td>${x.splice_starts_mm.length?x.splice_starts_mm.map(fmtm).join(', '):'No splice'}</td></tr>`).join('')}</table>`;
 const tag6=document.getElementById('fab6scopeTag');if(tag6){tag6.textContent=fab6Global?'WHOLE M70':'SELECTED BEAM';tag6.className='scope-tag'+(fab6Global?' scope-global':'')}
 const scope6=document.getElementById('fab6stockscope');if(scope6)scope6.innerHTML=fab6Global?`<b>Whole-network cutting stock:</b> all ${P.T12_stock_rods.length} parent rods.`:`<b>${r.run_id} stock trace:</b> ${stocks.length} parent rods supply its ${pieces.length} T12 pieces.`;
 const stockRows=fab6Global?P.T12_stock_rods:stocks;
 const st=document.getElementById('fab6stock');if(st)st.innerHTML=`<table class="tbl"><tr><th>Stock rod</th><th>Cut pieces / beam ownership</th><th>Used</th><th>Left</th></tr>${stockRows.map(x=>`<tr><td>${x.stock_rod_id}</td><td>${x.cut_piece_ids.map((id,i)=>{const pr=pieceRun(id),mine=pr===r.run_id;return `<span class="${mine?'piece-focus':''}">${mine?'★ ':''}${id} · ${pr||'?'} (${x.cut_lengths_mm[i]} mm)</span>`}).join('<br>')}</td><td>${x.used_mm} mm</td><td>${x.leftover_mm} mm</td></tr>`).join('')}</table><div class="legend">★ = selected beam. Unstarred pieces are shared co-cuts from the same 12 m rod.</div>`;

 const runT=T.run_summary.find(x=>x.run_id===r.run_id),links=T.links.filter(x=>x.run_id===r.run_id),L=r.centerline_length_m*1000;
 const f7=document.getElementById('fab7focus');if(f7)f7.innerHTML=`<b>Selected beam: ${r.run_id}</b> · source ${runT.source_link_count} · final ${runT.final_link_count} · ${runT.spacing_validation}`;
 const m7=document.getElementById('fab7metrics');if(m7)m7.innerHTML=`<div class="metric"><b>${runT.source_link_count}</b><span>frozen source links</span></div><div class="metric"><b>+${runT.additional_links_required}</b><span>lap-confinement added</span></div><div class="metric"><b>${runT.final_link_count}</b><span>final selected-run links</span></div><div class="metric"><b>${links.filter(x=>String(x.zone).includes('LAP')).length}</b><span>links in lap zones</span></div>`;
 const strip=document.getElementById('fab7strip');if(strip)strip.innerHTML=`<svg viewBox="0 0 900 150" style="width:100%;min-height:150px"><line x1="40" y1="75" x2="860" y2="75" stroke="#334155" stroke-width="5"/>${links.map(x=>{let xx=40+820*x.chainage_mm/L,c=String(x.zone).includes('LAP')?'#dc2626':String(x.zone).includes('JOINT')?'#2563eb':'#64748b';return `<line x1="${xx}" y1="54" x2="${xx}" y2="96" stroke="${c}" stroke-width="2"/>`}).join('')}<text x="40" y="125" font-size="13">Blue = joint · Red = lap · Grey = middle</text></svg>`;
 const coords=document.getElementById('fab7coords');if(coords)coords.innerHTML=`<table class="tbl"><tr><th>Link ID</th><th>Chainage</th><th>Zone</th><th>Cut</th></tr>${links.map(x=>`<tr><td>${x.link_id}</td><td>${x.chainage_mm} mm</td><td>${x.zone}</td><td>${x.cut_length_mm||1000} mm</td></tr>`).join('')}</table>`;
 const tag7=document.getElementById('fab7scopeTag');if(tag7){tag7.textContent=fab7Global?'WHOLE M70':'SELECTED BEAM';tag7.className='scope-tag'+(fab7Global?' scope-global':'')}
 const rr=fab7Global?T.run_summary:[runT],t7=document.getElementById('fab7table');if(t7)t7.innerHTML=`<table class="tbl"><tr><th>Run</th><th>Frozen source</th><th>Minimum with lap overlay</th><th>Added</th><th>Final</th></tr>${rr.map(x=>`<tr class="${x.run_id===r.run_id?'row-focus':''}"><td>${x.run_id}${x.run_id===r.run_id?' ★':''}</td><td>${x.source_link_count}</td><td>${x.minimum_required_with_lap_confinement}</td><td>${x.additional_links_required?'<b>+'+x.additional_links_required+'</b>':'0'}</td><td>${x.final_link_count}</td></tr>`).join('')}</table>`;

 const rel=relatedLeftovers(r.run_id),relLen=rel.reduce((a,x)=>a+x.length_mm,0);
 const f8=document.getElementById('fab8focus');if(f8)f8.innerHTML=`<b>Selected beam: ${r.run_id}</b> · filtered through parent-stock genealogy.`;
 const m8=document.getElementById('fab8metrics');if(m8)m8.innerHTML=`<div class="metric"><b>${rel.length}</b><span>related leftovers</span></div><div class="metric"><b>${(relLen/1000).toFixed(3)} m</b><span>related length</span></div><div class="metric"><b>${rel.filter(x=>x.diameter_mm===12).length} / ${rel.filter(x=>x.diameter_mm===8).length}</b><span>T12 / T8 pieces</span></div><div class="metric"><b>${rel.filter(x=>x.auto_reuse_screening_eligible).length}</b><span>reuse candidates</span></div>`;
 const g8=document.getElementById('fab8globalnote');if(g8)g8.innerHTML=`<b>Whole M70 inventory:</b> ${I.leftovers.length} tracked leftovers · ${I.summary.all_leftover_total_m.toFixed(3)} m total. Selected values are a genealogy filter, not a separate stockpile.`;
 const tag8=document.getElementById('fab8scopeTag');if(tag8){tag8.textContent=fab8Global?'ALL M70 LEFTOVERS':'SELECTED BEAM';tag8.className='scope-tag'+(fab8Global?' scope-global':'')}
 const invRows=fab8Global?I.leftovers:rel,t8=document.getElementById('fab8table');if(t8)t8.innerHTML=`<table class="tbl"><tr><th>Leftover ID</th><th>Dia</th><th>Length</th><th>Parent stock</th><th>Origin pieces / runs</th><th>Status</th><th>Reuse rule</th></tr>${invRows.map(x=>`<tr><td>${x.leftover_id}</td><td>T${x.diameter_mm}</td><td>${x.length_mm} mm</td><td>${x.parent_stock_rod_id}</td><td>${x.origin_cut_piece_ids.map(id=>{const pr=pieceRun(id),mine=pr===r.run_id;return `<span class="${mine?'piece-focus':''}">${mine?'★ ':''}${id}${pr?' · '+pr:''}</span>`}).join('<br>')}</td><td>${x.status}</td><td>${x.reuse_rule}</td></tr>`).join('')}</table><div class="legend">★ = origin piece belongs to selected beam. Shared parent rods can relate one leftover to multiple beams.</div>`;
}

function embeddedSnapshotText(){return document.getElementById('m70-json-snapshot').textContent}
function downloadEmbeddedSnapshot(){const blob=new Blob([embeddedSnapshotText()],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Narayani_M70_Embedded_JSON_Snapshot_v0.2.json';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},100)}
async function copyEmbeddedSnapshot(){try{await navigator.clipboard.writeText(embeddedSnapshotText());const e=document.getElementById('snapshot8meta');if(e)e.textContent='JSON snapshot copied to clipboard · '+SNAPSHOT.snapshot_id}catch(err){alert('Clipboard unavailable in this browser. Use Download JSON snapshot instead.')}}
function toggleEmbeddedSnapshot(){const e=document.getElementById('snapshot8pre');if(!e)return;e.style.display=e.style.display==='none'?'block':'none';if(e.style.display==='block'&&!e.textContent)e.textContent=JSON.stringify(SNAPSHOT,null,2)}
function renderSnapshotMeta(){const e=document.getElementById('snapshot8meta');if(!e)return;const v=SNAPSHOT.independent_validation.checks;const avail=SNAPSHOT.fabrication.inventory.leftovers.filter(x=>x.auto_reuse_screening_eligible);e.innerHTML=`<b>${SNAPSHOT.snapshot_id}</b> · payload SHA-256 ${SNAPSHOT.payload_sha256_before_hash_field}<br>${v.T12_stock_rods_12m} T12 stock rods · ${v.T8_stock_rods_12m} T8 stock rods · ${v.inventory_leftover_records} tracked leftover records · ${avail.length} auto-screening reuse candidates · validation ${SNAPSHOT.independent_validation.status}`}

function renderAll(){for(const id of ['plan1','plan2','plan3','plan4','plan5']){let e=document.getElementById(id);if(e)e.innerHTML=planSVG('multi')}for(const id of ['plan6','plan7','plan8']){let e=document.getElementById(id);if(e)e.innerHTML=planSVG('focus')}for(const id of ['sel2','sel3','sel4']){let e=document.getElementById(id);if(e)e.innerHTML=selectorHTML()}for(const id of ['metrics2','metrics3','metrics4']){let e=document.getElementById(id);if(e)e.innerHTML=metricsHTML()}for(const id of ['p1focus','focus4','focus5']){let e=document.getElementById(id);if(e)e.innerHTML=focusText()}let o=document.getElementById('order3');if(o){const m=sums();o.innerHTML=`<table class="tbl"><tr><th>Material / demand</th><th>Selected</th></tr><tr><td>M20 RCC</td><td>${m.rcc.toFixed(4)} m³</td></tr><tr><td>Cement</td><td>${m.cem.toFixed(2)} bags</td></tr><tr><td>Sand</td><td>${m.sand.toFixed(3)} m³</td></tr><tr><td>Aggregate</td><td>${m.agg.toFixed(3)} m³</td></tr><tr><td>T8 links</td><td>${m.links} pcs (${m.t8kg.toFixed(2)} kg installed)</td></tr><tr><td>T12 pre-terminal working fabrication</td><td>${m.preT12.toFixed(3)} m — NOT final selected-run procurement</td></tr></table><p class="muted"><b>Historical frozen BBS baseline:</b> ${DB.package_totals.T12_purchase_rods_12m_global_only} × 12 m rods for its earlier 48-splice abstraction. <b>Current spatial-code-compliant review proof:</b> ${FAB.proof.optimization.T12_stock_rods_12m} × 12 m rods, ${FAB.proof.optimization.T12_splice_events} legal lap events. Use Tab 6 for current fabrication review; the older BBS remains archived.</p>`}let d=document.getElementById('details4');if(d){const rr=selRows();d.innerHTML=rr.length?rr.map(detailCard).join(''):'<div class="muted" style="padding:12px">Select one or more PB runs from the list or map.</div>'}let e=document.getElementById('elev5');if(e)e.innerHTML=elevSVG();renderFabPages();renderSnapshotMeta()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.p).classList.add('active');renderAll()});renderAll();

