
(function(){
'use strict';
const S=JSON.parse(document.getElementById('m80-json').textContent);
const state={tab:'p1',component:'TANK',face:'EAST',family:S.bar_families[0].family_id,dia:'ALL',edge:'PCC_WEST',stock:null,offcut:null};
const $=id=>document.getElementById(id); const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function famById(id){return S.bar_families.find(x=>x.family_id===id)}
function componentLabel(id){const x=S.components.find(c=>c.id===id);return x?x.label:id}
function setComponent(id){state.component=id; const fs=S.bar_families.filter(f=>f.component===id); if(fs.length&&!fs.some(f=>f.family_id===state.family))state.family=fs[0].family_id; syncSelectors();renderAll()}
function setFamily(id){const f=famById(id);if(!f)return;state.family=id;state.component=f.component;state.dia=f.dia;syncSelectors();renderAll()}
function syncSelectors(){$('componentSel').value=state.component;$('faceSel').value=state.face;$('diaSel').value=state.dia;renderFamilyOptions();$('familySel').value=state.family}
function renderFamilyOptions(){const fam=S.bar_families.filter(f=>state.component==='TANK'||state.component==='PCC'||state.component==='B1'||state.component==='HAUNCH'||state.component==='MANHOLE'||state.component==='SUMP'?true:f.component===state.component);$('familySel').innerHTML=fam.map(f=>`<option value="${esc(f.family_id)}">${esc(f.mark)} · ${esc(f.label)}</option>`).join(''); if(!fam.some(f=>f.family_id===state.family)&&fam[0])state.family=fam[0].family_id;}
function initSelectors(){$('componentSel').innerHTML=S.components.map(c=>`<option value="${c.id}">${esc(c.label)}</option>`).join('');renderFamilyOptions();syncSelectors();}
function svgWrap(inner,vw=980,vh=620){return `<svg viewBox="0 0 ${vw} ${vh}" role="img">${inner}</svg>`}
function planSVG(edgeHi=''){const rows=S.spatial_context.rows,L=S.location.coordinates_mm;let xs=rows.flatMap(r=>[r.x1_mm,r.x2_mm]).concat([L.PCC.east]);let ys=rows.flatMap(r=>[r.y1_mm,r.y2_mm]).concat([L.PCC.north]);let xmin=Math.min(...xs)-500,xmax=Math.max(...xs)+1500,ymin=-250,ymax=Math.max(...ys)+650,W=980,H=620,p=42;let sx=x=>p+(x-xmin)/(xmax-xmin)*(W-2*p),sy=y=>H-p-(y-ymin)/(ymax-ymin)*(H-2*p);let q=`<rect width="${W}" height="${H}" fill="#f8fafc"/>`;for(const r of rows){let special=r.run_id==='PB-V8'?'PB-V8':(['PB-H1','PB-H2'].includes(r.run_id)?'H1-H2 BAY':'');q+=`<line class="geom ${state.component===special?'sel':''}" data-component="${special||'TANK'}" x1="${sx(r.x1_mm)}" y1="${sy(r.y1_mm)}" x2="${sx(r.x2_mm)}" y2="${sy(r.y2_mm)}" stroke="#334155" stroke-width="4"/><text x="${sx((r.x1_mm+r.x2_mm)/2)+3}" y="${sy((r.y1_mm+r.y2_mm)/2)-3}" font-size="8" fill="#64748b">${r.run_id}</text>`}let P=L.PCC,T=L.TANK_OUTER;let tankLinked=['TANK','BASE','WALL','COVER','B1','HAUNCH','MANHOLE','SUMP'].includes(state.component);q+=`<rect class="geom ${state.component==='PCC'?'sel':''}" data-component="PCC" x="${sx(P.west)}" y="${sy(P.north)}" width="${sx(P.east)-sx(P.west)}" height="${sy(P.south)-sy(P.north)}" fill="#fde68a" fill-opacity=".55" stroke="#d97706" stroke-width="2"/><rect class="geom ${tankLinked?'sel':''}" data-component="TANK" x="${sx(T.west)}" y="${sy(T.north)}" width="${sx(T.east)-sx(T.west)}" height="${sy(T.south)-sy(T.north)}" fill="#38bdf8" fill-opacity=".42" stroke="#0284c7" stroke-width="3"/>`;let mhx=T.west+1490,mhy=T.south+2190-600;let sw=T.west+1850,ss=T.south+150;q+=`<rect class="geom ${state.component==='MANHOLE'?'sel':''}" data-component="MANHOLE" x="${sx(mhx-600)}" y="${sy(mhy+600)}" width="${sx(mhx)-sx(mhx-600)}" height="${sy(mhy)-sy(mhy+600)}" fill="#fff" stroke="#ea580c" stroke-width="2"/><rect class="geom ${state.component==='SUMP'?'sel':''}" data-component="SUMP" x="${sx(sw)}" y="${sy(ss+150)}" width="${sx(sw+150)-sx(sw)}" height="${sy(ss)-sy(ss+150)}" fill="#fdba74" stroke="#ea580c" stroke-width="2"/>`;const ef=S.location.anchor.pb_east_face_x_mm;q+=`<line class="${edgeHi==='PB_FACE_TO_PCC'?'dimhi':''}" x1="${sx(ef)}" y1="${sy(1750)}" x2="${sx(P.west)}" y2="${sy(1750)}" stroke="#dc2626" stroke-width="2"/><text x="${(sx(ef)+sx(P.west))/2}" y="${sy(1750)-5}" text-anchor="middle" font-size="10" fill="#991b1b">1000 clear</text>`;if(edgeHi==='PCC_NORTH_H2')q+=`<line class="dimhi" x1="${sx(P.west)}" y1="${sy(P.north)}" x2="${sx(P.west)}" y2="${sy(S.location.anchor.bay.north_y_mm)}" stroke="#dc2626"/>`;q+=`<text x="${W-150}" y="42" font-size="12" font-weight="700" fill="#166534">EAST / ROAD →</text><text x="${W-70}" y="${H-18}" font-size="13" font-weight="700">N ↑</text>`;return svgWrap(q,W,H)}
function axonSVG(){const sel=state.component;const cls=id=>`geom ${sel===id?'sel':''}`;let q=`<rect width="700" height="500" fill="#f8fafc"/><polygon class="${cls('PCC')}" data-component="PCC" points="125,360 390,420 575,330 305,275" fill="#fde68a" stroke="#d97706" stroke-width="2"/><polygon class="${cls('BASE')}" data-component="BASE" points="145,345 385,398 550,318 305,267" fill="#94a3b8" stroke="#475569"/><polygon class="${cls('WALL')}" data-component="WALL" points="145,345 145,160 305,92 305,267" fill="#bae6fd" fill-opacity=".65" stroke="#0284c7"/><polygon class="${cls('WALL')}" data-component="WALL" points="305,92 545,145 550,318 305,267" fill="#7dd3fc" fill-opacity=".55" stroke="#0284c7"/><polygon class="${cls('COVER')}" data-component="COVER" points="145,160 385,210 545,145 305,92" fill="#cbd5e1" fill-opacity=".8" stroke="#475569"/><polygon class="${cls('MANHOLE')}" data-component="MANHOLE" points="382,141 438,153 477,136 420,124" fill="white" stroke="#ea580c" stroke-width="2"/><polygon class="${cls('HAUNCH')}" data-component="HAUNCH" points="155,333 196,342 155,302" fill="#f59e0b" stroke="#b45309"/><polygon class="${cls('HAUNCH')}" data-component="HAUNCH" points="535,307 497,319 535,274" fill="#f59e0b" stroke="#b45309"/><text x="355" y="470" text-anchor="middle" font-size="11">Schematic exploded axonometric — click components</text>`;return svgWrap(q,700,500)}
function sectionSVG(target=state.component){let cls=id=>`geom ${target===id?'sel':''}`;let q=`<rect width="700" height="480" fill="#f8fafc"/><rect class="${cls('COVER')}" data-component="COVER" x="120" y="65" width="460" height="25" fill="#cbd5e1" stroke="#64748b"/><rect class="${cls('WALL')}" data-component="WALL" x="120" y="90" width="28" height="280" fill="#bae6fd" stroke="#0284c7"/><rect class="${cls('WALL')}" data-component="WALL" x="552" y="90" width="28" height="280" fill="#bae6fd" stroke="#0284c7"/><rect class="${cls('BASE')}" data-component="BASE" x="120" y="370" width="460" height="32" fill="#94a3b8" stroke="#475569"/><rect class="${cls('PCC')}" data-component="PCC" x="105" y="402" width="490" height="16" fill="#fde68a" stroke="#d97706"/><rect class="${cls('B1')}" data-component="B1" x="148" y="90" width="15" height="23" fill="#a78bfa" stroke="#6d28d9"/><rect class="${cls('B1')}" data-component="B1" x="537" y="90" width="15" height="23" fill="#a78bfa" stroke="#6d28d9"/><polygon class="${cls('HAUNCH')}" data-component="HAUNCH" points="148,370 228,370 148,290" fill="#f59e0b" fill-opacity=".7" stroke="#b45309"/><polygon class="${cls('HAUNCH')}" data-component="HAUNCH" points="552,370 472,370 552,290" fill="#f59e0b" fill-opacity=".7" stroke="#b45309"/><rect class="${cls('SUMP')}" data-component="SUMP" x="320" y="390" width="32" height="28" fill="#fdba74" stroke="#ea580c"/><text x="350" y="447" text-anchor="middle" font-size="11">450×450 haunch · 150 base · 100 cover · 1950 clear internal height</text>`;return svgWrap(q,700,480)}
function wallElevationSVG(){let f=famById(state.family),vertical=f&&['WV-IN','WV-OUT'].includes(f.mark),horizontal=f&&['WH-IN','WH-OUT'].includes(f.mark),clip=f&&f.mark==='CLIP';let width=['NORTH','SOUTH'].includes(state.face)?2000:2700;let W=720,H=430,x0=80,y0=65,x1=640,y1=340,q=`<rect width="${W}" height="${H}" fill="#f8fafc"/><rect x="${x0}" y="${y0}" width="${x1-x0}" height="${y1-y0}" fill="#e0f2fe" stroke="#0284c7" stroke-width="3"/>`;for(let i=0;i<=12;i++){let x=x0+(x1-x0)*i/12;q+=`<line class="wallbar ${vertical?'hi':''}" x1="${x}" y1="${y0+8}" x2="${x}" y2="${y1-8}"/>`}for(let j=0;j<=9;j++){let y=y0+(y1-y0)*j/9;q+=`<line class="wallbar ${horizontal?'hi':''}" x1="${x0+8}" y1="${y}" x2="${x1-8}" y2="${y}"/>`}if(clip)for(let i=2;i<11;i+=3)for(let j=2;j<8;j+=3)q+=`<rect x="${x0+(x1-x0)*i/12-5}" y="${y0+(y1-y0)*j/9-5}" width="10" height="10" fill="#dc2626"/>`;q+=`<text x="360" y="385" text-anchor="middle" font-size="12" font-weight="700">${state.face} wall · clear face length ${width} mm</text><text x="360" y="405" text-anchor="middle" font-size="10">Directional field schematic; BBS family totals are whole-perimeter source authority</text>`;return svgWrap(q,W,H)}
function basePlanSVG(){let f=famById(state.family),mark=f&&f.component==='BASE'?f.mark:'a',q=`<rect width="700" height="500" fill="#f8fafc"/><rect x="115" y="75" width="420" height="330" fill="#e2e8f0" stroke="#475569" stroke-width="3"/><rect x="350" y="275" width="32" height="32" fill="#fed7aa" stroke="#ea580c"/><text x="366" y="323" text-anchor="middle" font-size="9">sump</text>`;for(let i=0;i<12;i++){let x=135+i*34;q+=`<line class="barbase ${['a','c_short'].includes(mark)?'barhi':''}" x1="${x}" y1="90" x2="${x}" y2="390"/>`}for(let j=0;j<10;j++){let y=95+j*31;q+=`<line class="barbase ${['b','c_long'].includes(mark)?'barhi':''}" x1="130" y1="${y}" x2="520" y2="${y}"/>`}q+=`<text x="325" y="450" text-anchor="middle" font-size="11">Selected family: ${esc(mark)} · highlighted direction only</text>`;return svgWrap(q,700,500)}
function coverPlanSVG(){let f=famById(state.family),mark=f&&f.component==='COVER'?f.mark:'d',D=S.governed_bbs.cover.reinforcement.d,E=S.governed_bbs.cover.reinforcement.e,q=`<rect width="700" height="500" fill="#f8fafc"/><rect x="115" y="70" width="420" height="340" fill="#e2e8f0" stroke="#475569" stroke-width="3"/><rect x="330" y="135" width="110" height="90" fill="white" stroke="#ea580c" stroke-width="3"/><text x="385" y="185" text-anchor="middle" font-size="11">600×600 manhole</text>`;for(const pos of D.positions_mm){let x=115+420*pos/2300;q+=`<line class="barbase ${mark==='d'?'barhi':''}" x1="${x}" y1="78" x2="${x}" y2="402"/>`}for(const pos of E.positions_mm){let y=70+340*pos/3000;q+=`<line class="barbase ${mark==='e'?'barhi':''}" x1="122" y1="${y}" x2="528" y2="${y}"/>`}if(mark==='CORNER')q+=`<line class="barhi" x1="115" y1="70" x2="175" y2="130"/><line class="barhi" x1="535" y1="70" x2="475" y2="130"/><line class="barhi" x1="115" y1="410" x2="175" y2="350"/><line class="barhi" x1="535" y1="410" x2="475" y2="350"/>`;q+=`<text x="325" y="455" text-anchor="middle" font-size="11">d/e positions use source-stored coordinates; red = selected family</text>`;return svgWrap(q,700,500)}
function cutShapeSVG(){const f=famById(state.family);if(!f)return svgWrap('<text x="30" y="60">No bar family selected</text>',700,300);let q=`<rect width="700" height="300" fill="#f8fafc"/><text x="30" y="35" font-size="15" font-weight="700">${esc(f.mark)} · ${esc(f.label)}</text>`;let y=150;if(f.mark.startsWith('WH-'))q+=`<rect x="210" y="90" width="280" height="120" rx="10" fill="none" stroke="#dc2626" stroke-width="5"/>`;else if(f.mark==='CLIP')q+=`<path d="M250 180 L250 110 L450 110 L450 180" fill="none" stroke="#dc2626" stroke-width="5"/>`;else if(['b','c_short','c_long'].includes(f.mark))q+=`<path d="M180 190 L180 120 L520 120 L520 190" fill="none" stroke="#dc2626" stroke-width="5"/>`;else if(f.mark==='CORNER')q+=`<path d="M260 190 L350 100 L440 190" fill="none" stroke="#dc2626" stroke-width="5"/>`;else q+=`<line x1="170" y1="145" x2="530" y2="145" stroke="#dc2626" stroke-width="5"/>`;q+=`<text x="350" y="245" text-anchor="middle" font-size="13">Fabrication cut = ${Number(f.cut_m).toFixed(3)} m · ${f.dia}</text><text x="350" y="270" text-anchor="middle" font-size="10">Shape is schematic unless the family source explicitly stores complete bend geometry</text>`;return svgWrap(q,700,300)}
function stockVizSVG(rod){if(!rod)return svgWrap('<text x="30" y="60">Select a stock rod</text>',760,240);let x0=70,x1=690,y=95,total=12,q=`<rect width="760" height="240" fill="#f8fafc"/><line x1="${x0}" y1="${y}" x2="${x1}" y2="${y}" stroke="#334155" stroke-width="12" stroke-linecap="round"/>`;let x=x0;for(let i=0;i<rod.cuts_m.length;i++){let w=(x1-x0)*rod.cuts_m[i]/total;q+=`<line x1="${x}" y1="70" x2="${x}" y2="120" stroke="#dc2626" stroke-width="2"/><text x="${x+w/2}" y="60" text-anchor="middle" font-size="10">${rod.cuts_m[i]}m</text>`;x+=w}q+=`<line x1="${x}" y1="70" x2="${x}" y2="120" stroke="#16a34a" stroke-width="2"/><text x="${(x+x1)/2}" y="145" text-anchor="middle" font-size="11" fill="#166534">offcut ${rod.offcut_m.toFixed(3)} m</text><text x="380" y="205" text-anchor="middle" font-size="12" font-weight="700">${rod.stock_id} · ${rod.dia} · 12.000 m parent rod</text>`;return svgWrap(q,760,240)}
function lineageSVG(off){if(!off)return svgWrap('<text x="30" y="60">Select a leftover</text>',760,300);let rod=S.stock_instances.find(r=>r.stock_id===off.parent_stock_id);return svgWrap(`<rect width="760" height="300" fill="#f8fafc"/><rect x="35" y="110" width="150" height="58" rx="8" fill="#e2e8f0" stroke="#64748b"/><text x="110" y="135" text-anchor="middle" font-size="11">Parent stock</text><text x="110" y="152" text-anchor="middle" font-size="10">${esc(off.parent_stock_id)}</text><path d="M185 139 L275 139" stroke="#64748b" stroke-width="2"/><rect x="275" y="90" width="190" height="98" rx="8" fill="#dbeafe" stroke="#2563eb"/><text x="370" y="117" text-anchor="middle" font-size="11">Cut pattern</text><text x="370" y="140" text-anchor="middle" font-size="10">${rod?rod.cuts_m.join(' + '):''}</text><text x="370" y="162" text-anchor="middle" font-size="10">used ${rod?rod.used_m.toFixed(3):''} m</text><path d="M465 139 L555 139" stroke="#64748b" stroke-width="2"/><rect x="555" y="110" width="165" height="58" rx="8" fill="#dcfce7" stroke="#16a34a"/><text x="637" y="135" text-anchor="middle" font-size="11">Leftover</text><text x="637" y="152" text-anchor="middle" font-size="10">${off.length_m.toFixed(3)} m · ${off.status}</text><text x="380" y="245" text-anchor="middle" font-size="10">Origin component links are cut-length-family candidates where source histogram does not preserve unique piece IDs.</text>`,760,300)}
function renderStateSummaries(){let f=famById(state.family),txt=`<b>${componentLabel(state.component)}</b> · face ${state.face} · family ${f?esc(f.mark):'—'} · diameter ${state.dia}`;['stateSummary1','stateSummary3'].forEach(id=>{if($(id))$(id).innerHTML=txt})}
function renderPlans(){$('plan1').innerHTML=planSVG();$('plan2').innerHTML=planSVG(state.edge)}
function renderSetout(){const L=S.location;let rows=[['PB_FACE_TO_PCC','PB-V8 east face → PCC west','1000 mm'],['PCC_WEST','PCC west x',L.coordinates_mm.PCC.west.toFixed(3)+' mm'],['PCC_EAST','PCC east x',L.coordinates_mm.PCC.east.toFixed(3)+' mm'],['PCC_SOUTH','PCC south / H1',L.coordinates_mm.PCC.south.toFixed(0)+' mm'],['PCC_NORTH_H2','PCC north → H2','400 mm clear'],['TANK_OUTER','Tank outer x/y','2300 × 3000 mm']];$('setoutTable').innerHTML='<table><tr><th>Control</th><th>Value</th></tr>'+rows.map(r=>`<tr class="pick ${state.edge===r[0]?'sel':''}" data-edge="${r[0]}"><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')+'</table>';$('edgeInfo').innerHTML='<b>Set-out focus:</b> '+esc(state.edge)}
function renderAxon(){$('axon').innerHTML=axonSVG();$('componentChips').innerHTML=S.components.map(c=>`<button class="chip ${state.component===c.id?'active':''}" data-component="${c.id}">${esc(c.label)}</button>`).join('');let comp=S.components.find(c=>c.id===state.component);$('componentFacts').innerHTML=`<div class="kpi"><b>${esc(comp?comp.label:state.component)}</b><span class="muted">Views: ${comp?comp.view_modes.join(', '):'spatial control'}</span></div>`}
function renderSections(){$('sectionView').innerHTML=sectionSVG();$('qtoSection').innerHTML=sectionSVG(state.component);$('edgeSection').innerHTML=sectionSVG(state.component);$('elevationView').innerHTML=wallElevationSVG();$('wallElev').innerHTML=wallElevationSVG();$('elevTitle').textContent=state.face+' wall elevation';$('wallVizTitle').textContent=state.face+' wall reinforcement';$('elevNote').innerHTML='<b>Selected family:</b> '+esc((famById(state.family)||{mark:'—'}).mark)+' · whole-perimeter BBS family unless source says otherwise.'}
function renderQTO(){$('qtoTable').innerHTML='<table><tr><th>Component</th><th>m³</th><th>Visual</th></tr>'+S.concrete_components.map(r=>`<tr class="pick ${state.component===r.id?'sel':''}" data-component="${r.id}"><td>${esc(r.label)}</td><td>${Number(r.m3).toFixed(5)}</td><td>${r.view}</td></tr>`).join('')+'</table>';$('qtoInfo').innerHTML=`<b>Total current M20 RCC:</b> ${S.haunch_current.quantity.TOTAL_M20_RCC_m3.toFixed(5)} m³ · PCC ${S.haunch_current.quantity.PCC_m3.toFixed(3)} m³`}
function familyRows(comp){return S.bar_families.filter(f=>f.component===comp)}
function tableForFamilies(comp,id){let a=familyRows(comp);$(id).innerHTML='<table><tr><th>Mark</th><th>Dia</th><th>Qty</th><th>Cut m</th><th>Weight kg</th></tr>'+a.map(f=>`<tr class="pick ${state.family===f.family_id?'sel':''}" data-family="${esc(f.family_id)}"><td>${esc(f.mark)}</td><td>${f.dia}</td><td>${f.qty}</td><td>${Number(f.cut_m).toFixed(3)}</td><td>${f.weight_kg==null?'—':Number(f.weight_kg).toFixed(2)}</td></tr>`).join('')+'</table>'}
function renderBase(){$('basePlan').innerHTML=basePlanSVG();tableForFamilies('BASE','baseTable');let f=famById(state.family);$('baseInfo').innerHTML=f&&f.component==='BASE'?`<b>${esc(f.mark)}</b> · ${esc(f.label)} · ${f.dia} · qty ${f.qty} · cut ${Number(f.cut_m).toFixed(3)} m`:'Select a base row.'}
function renderWall(){tableForFamilies('WALL','wallTable');let f=famById(state.family);$('wallInfo').innerHTML=f&&f.component==='WALL'?`<b>${esc(f.mark)}</b> · ${esc(f.label)} · qty ${f.qty} · cut ${Number(f.cut_m).toFixed(3)} m`:'Select a wall row.'}
function renderCover(){$('coverPlan').innerHTML=coverPlanSVG();tableForFamilies('COVER','coverTable');let f=famById(state.family);$('coverInfo').innerHTML=f&&f.component==='COVER'?`<b>${esc(f.mark)}</b> · ${esc(f.label)} · qty ${f.qty} · cut ${Number(f.cut_m).toFixed(3)} m`:`<b>${componentLabel(state.component)}</b> · click cover family or B1/haunch section.`}
function renderShape(){$('shapeViz').innerHTML=cutShapeSVG();let f=famById(state.family);$('shapeInfo').innerHTML=f?`<b>${esc(f.family_id)}</b><br>${esc(f.provenance)}<br><span class="muted">${esc(f.method)}</span>`:'No family';$('familyTable').innerHTML='<table><tr><th>Component</th><th>Mark</th><th>Dia</th><th>Cut</th><th>Provenance</th></tr>'+S.bar_families.filter(f=>state.dia==='ALL'||f.dia===state.dia).map(f=>`<tr class="pick ${state.family===f.family_id?'sel':''}" data-family="${esc(f.family_id)}"><td>${f.component}</td><td>${esc(f.mark)}</td><td>${f.dia}</td><td>${Number(f.cut_m).toFixed(3)}</td><td>${esc(f.provenance)}</td></tr>`).join('')+'</table>'}
function stockFiltered(){return S.stock_instances.filter(r=>state.dia==='ALL'||r.dia===state.dia)}
function renderStock(){let a=stockFiltered();if(!state.stock||!a.some(x=>x.stock_id===state.stock))state.stock=a[0]?.stock_id||null;$('stockTable').innerHTML='<table><tr><th>Rod</th><th>Dia</th><th>Cuts</th><th>Used</th><th>Offcut</th></tr>'+a.map(r=>`<tr class="pick ${state.stock===r.stock_id?'sel':''}" data-stock="${r.stock_id}"><td>${r.stock_id}</td><td>${r.dia}</td><td>${r.cuts_m.join(' + ')}</td><td>${r.used_m.toFixed(3)}</td><td>${r.offcut_m.toFixed(3)}</td></tr>`).join('')+'</table>';let rod=S.stock_instances.find(r=>r.stock_id===state.stock);$('stockViz').innerHTML=stockVizSVG(rod);$('stockInfo').innerHTML=rod?`<b>${rod.stock_id}</b> · ${rod.genealogy_strength}`:'No rod';$('stockCandidates').innerHTML=rod?'<h4>Candidate installed families from exact cut-length matches</h4>'+ (rod.candidate_families.length?'<ul>'+rod.candidate_families.map(c=>`<li><button class="chip" data-family="${esc(c.family_id)}">${esc(c.component+' · '+c.mark+' · '+c.label)}</button></li>`).join('')+'</ul>':'<div class="warn card">No unique family link encoded for these cut lengths.</div>'):''}
function invFiltered(){let q=$('invSearch').value.trim().toLowerCase(),min=Number($('minLeft').value||0),st=$('invStatus').value;return S.leftover_inventory.filter(x=>(state.dia==='ALL'||x.dia===state.dia)&&x.length_m>=min&&(st==='ALL'||x.status===st)&&(!q||(x.leftover_id+' '+x.parent_stock_id).toLowerCase().includes(q)))}
function renderInv(){let a=invFiltered();if(!state.offcut||!a.some(x=>x.leftover_id===state.offcut))state.offcut=a[0]?.leftover_id||null;$('invTable').innerHTML='<table><tr><th>Leftover</th><th>Dia</th><th>Parent</th><th>Length</th><th>Status</th></tr>'+a.map(x=>`<tr class="pick ${state.offcut===x.leftover_id?'sel':''}" data-offcut="${x.leftover_id}"><td>${x.leftover_id}</td><td>${x.dia}</td><td>${x.parent_stock_id}</td><td>${x.length_m.toFixed(3)} m</td><td>${x.status}</td></tr>`).join('')+'</table>';let off=S.leftover_inventory.find(x=>x.leftover_id===state.offcut);$('invViz').innerHTML=lineageSVG(off);$('invInfo').innerHTML=off?`<b>${off.leftover_id}</b> · parent ${off.parent_stock_id} · ${off.length_m.toFixed(3)} m · ${off.reuse_screening}<br><span class="muted">Candidate origin families from exact cut-length matches:</span><div class="chips" style="margin-top:6px">${off.candidate_origin_families.length?off.candidate_origin_families.map(c=>`<button class="chip" data-family="${esc(c.family_id)}">${esc(c.component+' · '+c.mark)}</button>`).join(''):'none encoded'}</div>`:'No leftover selected.'}
function renderSources(){let refs=S.source_refs;$('sourceTable').innerHTML='<table><tr><th>Authority</th><th>Drive ID</th></tr>'+Object.entries(refs).map(([k,v])=>`<tr><td>${esc(k)}</td><td class="mono">${esc(v)}</td></tr>`).join('')+'</table>';$('validationSummary').innerHTML=`<b>Snapshot:</b> ${S.snapshot_id} · 12 tabs · ${S.stock_instances.length} tank stock instances · ${S.leftover_inventory.length} leftover records · location inside H1–H2 = ${S.location.checks.PCC_inside_H1_H2_bay}`}
function renderAll(){renderStateSummaries();renderPlans();renderSetout();renderAxon();renderSections();renderQTO();renderBase();renderWall();renderCover();renderShape();renderStock();renderInv();renderSources();document.querySelectorAll('[data-component]').forEach(e=>e.classList.toggle('sel',e.dataset.component===state.component));document.querySelectorAll('[data-family]').forEach(e=>e.classList.toggle('sel',e.dataset.family===state.family));}
function activateTab(id){state.tab=id;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));renderAll()}
initSelectors();
$('componentSel').addEventListener('change',e=>setComponent(e.target.value));$('faceSel').addEventListener('change',e=>{state.face=e.target.value;renderAll()});$('familySel').addEventListener('change',e=>setFamily(e.target.value));$('diaSel').addEventListener('change',e=>{state.dia=e.target.value;renderAll()});
$('invSearch').addEventListener('input',renderInv);$('minLeft').addEventListener('input',renderInv);$('invStatus').addEventListener('change',renderInv);$('jsonBtn').addEventListener('click',()=>{let p=$('jsonPre');p.style.display=p.style.display==='none'?'block':'none';p.textContent=JSON.stringify(S,null,2)});
document.body.addEventListener('click',e=>{let t=e.target.closest('[data-tab],[data-component],[data-family],[data-edge],[data-stock],[data-offcut],[data-dia-button]');if(!t)return;if(t.dataset.tab)activateTab(t.dataset.tab);else if(t.dataset.component)setComponent(t.dataset.component);else if(t.dataset.family)setFamily(t.dataset.family);else if(t.dataset.edge){state.edge=t.dataset.edge;renderAll()}else if(t.dataset.stock){state.stock=t.dataset.stock;let r=S.stock_instances.find(x=>x.stock_id===state.stock);if(r)state.dia=r.dia;syncSelectors();renderAll()}else if(t.dataset.offcut){state.offcut=t.dataset.offcut;let o=S.leftover_inventory.find(x=>x.leftover_id===state.offcut);if(o)state.dia=o.dia;syncSelectors();renderAll()}else if(t.dataset.diaButton){state.dia=t.dataset.diaButton;syncSelectors();renderAll()}});
document.body.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('tr.pick')){e.preventDefault();e.target.click()}});
renderAll();
})();

